### ISSUE TITLE
Not Production Ready?

### ISSUE THREAD

**Issue by elijah-potter** [ron4fun/SharpHash#1]
Hi, I would really like to use SharpHash in a project, but the README states that it is not production ready. I am just wondering if that is still true, or what the timeline is for getting it to that state.

**Comment by ron4fun** [comment]
Hello, I appreciate your interest in my library for now it is not
production ready but in two weeks time it will be.
I hope you can wait this long?

Kind regards.

**Comment by elijah-potter** [comment]
No problem. There is no rush. Your library is perfect for my needs. Thank you.
