### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by elijah-potter** [ron4fun/SharpHash#2]
I am curious if there was a nuget package or if there were plans for one? I would be happy to create one, but I am sure you would rather.

**Comment by ron4fun** [comment]
Thanks for asking. I am already working on one.

**Comment by Xor-el** [comment]
@chilipepperhott , if you are still interested in the nuget package, here is my [HashLib4CSharp Implementation](https://github.com/Xor-el/HashLib4CSharp), disclaimer: I am the author of the original HashLib4Pascal library.
Link to the nuget package can be found on my repository README.
Regards.
